Adds an ideal ROT functionality to mpz-ot-core
privacy-ethereum/mpz pull request #102
Opened 2024-02-16 17:36 UTC by th4s

2024-02-21 18:46 UTC, sinui0 requested changes
lgtm other than a few things

2024-02-21 18:46 UTC, sinui0 commented on ot/mpz-ot-core/src/ideal/ideal_rot.rs
> +    }
This is just a unit test and shouldn't be part of the API

2024-02-21 18:46 UTC, sinui0 commented on ot/mpz-ot-core/src/ideal/ideal_rot.rs
> +#[allow(missing_docs)]
Please fix spacing between struct defs and document this struct

2024-02-21 18:46 UTC, sinui0 commented on ot/mpz-ot-core/src/ideal/ideal_rot.rs
> +    }
We can implement `Default` as well.

2024-02-21 18:46 UTC, sinui0 commented on ot/mpz-ot-core/src/ideal/ideal_rot.rs
> +pub struct IdealROT {
```suggestion
#[derive(Debug)]
pub struct IdealROT {
```

2024-02-21 19:15 UTC, th4s commented on ot/mpz-ot-core/src/ideal/ideal_rot.rs
> +    }
It is already implemented.

2024-02-21 19:15 UTC, th4s commented on ot/mpz-ot-core/src/ideal/ideal_rot.rs
> +pub struct IdealROT {
Unfortunately this does not work, because `Prg` does not implement `Debug`.

2024-02-21 21:40 UTC, sinui0 commented on ot/mpz-ot-core/src/ideal/ideal_rot.rs
> +pub struct IdealROT {
Pls add `Debug` to `Prg` (probably opaque impl to hide the key)

2024-02-21 21:42 UTC, sinui0 commented on ot/mpz-ot-core/src/ideal/ideal_rot.rs
> +    }
This doesn't belong here, it just adds noise to the impl block. This function should just be inlined in the unit test

2024-02-22 05:00 UTC, sinui0 approved these changes

2024-02-28 06:08 UTC, themighty1 approved these changes

2024-02-28 08:01 UTC, th4s commented
I will wait for the IO refactor before merging this.

2024-03-07 17:14 UTC, sinui0 commented
lgtm

2024-03-07 17:15 UTC, merged