feat: generic circuit struct
privacy-ethereum/mpz pull request #123
Opened 2024-05-02 21:48 UTC by brech1

--wip--

2024-05-06 15:32 UTC, brech1 commented
- The binary module is just an example of how to use the generic structs with a basic binary circuit.
- The way we decide to deal with declaring inputs and outputs of the circuit, or this kind of "builder api" can shape the interface or even remove it completely. Current implementation is just a basic one to test the structure. In this point perhaps we could prioritize to make things easier to deal with `mpz` or adapt to the old structure as much as possible.

2024-05-12 13:46 UTC, brech1 commented
The model has been updated with few key changes:

- Both circuit and gates can be modeled as:
  - components: blocks with inputs and outputs
  - executables: can perform external operations on memory
  
A key change is that the execution is defined externally on both, by part of an `Executor`.

This means that each structure can perform multiple operations with the same configuration.

Binary example module is yet to be updated with this new blocks.

2024-05-27 22:45 UTC, sinui0 reviewed
I'm not sure I'm convinced of the execution abstractions here. For now I think it would be easiest to just stick to developing the `Circuit` type and have it enforce the invariants we discussed previously, eg topological sort etc. We can add execution in a follow up PR.

2024-06-04 04:08 UTC, sinui0 requested changes
Nice, this will be a much more flexible base for our circuit models!

Some requests :pray:

2024-06-04 04:08 UTC, sinui0 commented on crates/mpz-circuits-generic/src/circuit.rs
> +pub enum CircuitError {
```suggestion
pub enum CircuitBuilderError {
```

2024-06-04 04:08 UTC, sinui0 commented on crates/mpz-circuits-generic/src/lib.rs
> +pub mod model;
Let's make these private and export needed types

2024-06-04 04:08 UTC, sinui0 commented on crates/mpz-circuits-generic/tests/sorting.rs
> +mod tests {
Can we add a couple test cases?

1. Unordered gates
2. Disconnected gate
3. Node ids are contiguous
4. Node ids are ordered: { input nodes } .. { output nodes }

2024-06-04 04:08 UTC, sinui0 commented on crates/mpz-circuits-generic/src/model.rs
> +    fn get_inputs(&self) -> Vec<usize>;
We should return `impl Iterator<Item = &Node>` so that it's possible for the ids to be stack allocated, ie `[Node; 2]`, or some other data structure. Otherwise every call to this function is going to incur a heap allocation.

2024-06-04 04:08 UTC, sinui0 commented on crates/mpz-circuits-generic/src/model.rs
Can we add a `Node` newtype, as we currently have in `mpz-circuits`. Gives us better typing. Perhaps we should also switch it from `usize` to `u32` so the circuit isn't needlessly twice the size on 64 bit archs.

2024-06-05 12:45 UTC, brech1 commented on crates/mpz-circuits-generic/src/model.rs
- I think that adding a `Node` type is not strictly necessary so I wouldn't implement it in the model. Don't see how much of an improvement this extra typing could provide on our level, perhaps implementers could add this layer themselves.
- The input or output is intended to be a position on a linear memory array so it will be `usize` in the end, on 64-bit architectures you'll have to complete the address to access an index.

But both are good suggestions, I could be missing something!

2024-06-05 21:18 UTC, sinui0 commented on crates/mpz-circuits-generic/src/model.rs
> Don't see how much of an improvement this extra typing could provide on our level

It's all about the public API: What do you want to commit to? Using `usize` commits to that underlying representation, whereas a `Node(u32)` type allows us to constrain the data type and the traits which a node implements. For example why would a node implement `Add`? `usize` does. Do we want to allow it to be mutated? How might that affect certain invariants we have elsewhere? This is less an issue for private types, but this is explicitly part of the crates pub api.

> The input or output is intended to be a position on a linear memory array so it will be usize in the end

Yes it will be used to index into linear memory, but a `Vec<u32>` is half the size of a `Vec<u64>`, and hence a `Vec<Gate>` will be half the size if `Node` is backed by a `u32` instead of `u64` on 64-bit archs.

2024-06-07 15:49 UTC, brech1 commented on crates/mpz-circuits-generic/tests/sorting.rs
> +mod tests {
I added the disconnected gate test, but I'm confused about testing the node ids, in which way they should be contiguous or ordered? The order is based on that the gates should be ready to be processed, so node ids are not always contiguous or ordered

2024-06-07 17:09 UTC, sinui0 commented on crates/mpz-circuits-generic/tests/sorting.rs
> +        );
This should be an error, no? A circuit should not have disconnected gates

2024-06-07 17:09 UTC, sinui0 commented on crates/mpz-circuits-generic/tests/sorting.rs
> +mod tests {
> The order is based on that the gates should be ready to be processed

Exactly, so the node id should correspond to the gate position. For example:

```rust
assert!(gates.windows(2).map(|window| window[1].out.0 == window[0].out.0 + 1).all());
```

This asserts the nodes are ordered and contiguous.

2024-06-07 17:09 UTC, sinui0 commented on crates/mpz-circuits-generic/src/model.rs
> +pub struct Node<T> {
Why is this generic?

2024-06-10 23:54 UTC, closed without merging

2024-06-10 23:54 UTC, brech1 commented
Closing for #156