add ferret with io
privacy-ethereum/mpz pull request #137
Opened 2024-05-18 04:37 UTC by xiangxiecrypto

- [x] SPCOT with io
- [x] MPCOT with io
- [x] Ferret with io

Note that in the Ferret implementation, we need two random COTs. One for MPCOT (SPCOT), which can be IKNP-type (KOS) Random COTs. The other one is for the setup in Ferret, which will be Ferret with smaller parameters.

All the parameters will be chosen when the lpn estimator is done.

2024-05-23 16:24 UTC, sinui0 commented
Great, thanks! Will review soon.

2024-05-31 16:46 UTC, sinui0 requested changes
Excited to see it all come together! :fire:

I have some requests which should simplify things quite a bit.

1. For MPCOT, I believe we can eliminate a lot of duplication by encapsulating the different LPN types (regular/uniform). Instead of having two types you can add an argument to the constructor and handle it behind the API. The core types can remain separate but the IO wrapper can be unified.
2. The `check` and `finalize` methods should not be exposed in the public API. When calling `extend` the user should just provide the number of OTs they want and you handle the entire process for them. Additionally, `extend` should not return the OTs, it should buffer them internally because it is used during the preprocessing phase. This buffering should be performed in the core crate, the same as how we do it for KOS.

For example, here is what the public API could look like:

```rust
impl<RandomCOT> Sender<RandomCot> {
  pub fn new(lpn_type: LpnType, rcot: RandomCOT) -> Self { .. }

  pub async fn setup<Ctx: Context>(&mut self, ctx: &mut Ctx) 
    -> Result<(), SenderError> { .. }
  
  /// Preprocesses `count` OTs.
  pub async fn extend<Ctx: Context>(&mut self, ctx: &mut Ctx, count: usize)
    -> Result<(), SenderError> { .. }
}
```

This applies to SPCOT, MPCOT and Ferret

2024-05-31 16:46 UTC, sinui0 commented on crates/mpz-ot/src/ferret/mpcot/sender_regular.rs
> +        println!("here");
left over

2024-05-31 16:46 UTC, sinui0 commented on crates/mpz-ot-core/src/ferret/spcot/sender.rs
> +};
```suggestion
#[cfg(feature = "rayon")]
use rayon::iter::{
    IndexedParallelIterator, IntoParallelRefIterator, IntoParallelRefMutIterator, ParallelIterator,
};
```

2024-05-31 16:46 UTC, sinui0 commented on crates/mpz-ot-core/src/ferret/spcot/receiver.rs
> +};
```suggestion
#[cfg(feature = "rayon")]
use rayon::iter::{
    IndexedParallelIterator, IntoParallelRefIterator, IntoParallelRefMutIterator, ParallelIterator,
};
```

2024-05-31 16:46 UTC, sinui0 commented on crates/mpz-ot-core/src/ferret/spcot/receiver.rs
> +                .map(|(((((alpha, ms), sum), h), ts), tree)| (alpha, ms, sum, h, ts, tree));
```suggestion
                let iter = alphas
                    .par_iter()
                    .zip(ms_s.par_iter())
                    .zip(sum_s.par_iter())
                    .zip(hs.par_iter())
                    .zip(ts_s.par_iter())
                    .zip(trees.par_iter_mut())
                    .map(|(((((alpha, ms), sum), h), ts), tree)| (alpha, ms, sum, h, ts, tree));
```

2024-05-31 16:46 UTC, sinui0 commented on crates/mpz-ot-core/src/ferret/spcot/receiver.rs
> +                .map(|(((((alpha, ms), sum), h), ts), tree)| (alpha, ms, sum, h, ts, tree));
```suggestion
                let iter = alphas
                    .iter()
                    .zip(ms_s.iter())
                    .zip(sum_s.iter())
                    .zip(hs.iter())
                    .zip(ts_s.iter())
                    .zip(trees.iter_mut())
                    .map(|(((((alpha, ms), sum), h), ts), tree)| (alpha, ms, sum, h, ts, tree));
```

2024-05-31 16:53 UTC, sinui0 commented on crates/mpz-ot/src/ferret/sender.rs
> +        setup_rcot: &mut impl RandomCOTSender<Ctx, Block>,
Why is this passed in here? I would just call the instance we pass into MPCOT

2024-06-04 14:05 UTC, xiangxiecrypto commented
> Excited to see it all come together! 🔥
> 
> I have some requests which should simplify things quite a bit.
> 
> 1. For MPCOT, I believe we can eliminate a lot of duplication by encapsulating the different LPN types (regular/uniform). Instead of having two types you can add an argument to the constructor and handle it behind the API. The core types can remain separate but the IO wrapper can be unified.

Yep, we can simplify mpcot to just one type.

> 2. The `check` and `finalize` methods should not be exposed in the public API. When calling `extend` the user should just provide the number of OTs they want and you handle the entire process for them. Additionally, `extend` should not return the OTs, it should buffer them internally because it is used during the preprocessing phase. This buffering should be performed in the core crate, the same as how we do it for KOS.

Maybe we can keep spcot and mpcot internal apis, since they are only called by ferret. In this case, we do not need to keep all the output in internal states, it is much easier to be integrated by ferret.

As to `finalize`, I meant to explicitly close the extension procedure of ferret. In KOS, the state will automatically turn to `Complete` after the check procedure (if I understand correctly). While in ferret, it will always allow us to extend, unless we manually turn it off with `finalize`.

> 
> For example, here is what the public API could look like:
> 
> ```rust
> impl<RandomCOT> Sender<RandomCot> {
>   pub fn new(lpn_type: LpnType, rcot: RandomCOT) -> Self { .. }
> 
>   pub async fn setup<Ctx: Context>(&mut self, ctx: &mut Ctx) 
>     -> Result<(), SenderError> { .. }
>   
>   /// Preprocesses `count` OTs.
>   pub async fn extend<Ctx: Context>(&mut self, ctx: &mut Ctx, count: usize)
>     -> Result<(), SenderError> { .. }
> }
> ```
> 
> This applies to SPCOT, MPCOT and Ferret

2024-06-04 14:07 UTC, xiangxiecrypto commented on crates/mpz-ot/src/ferret/sender.rs
> +        setup_rcot: &mut impl RandomCOTSender<Ctx, Block>,
can you please be more specific?
I think the MPCOT instance is determined by the lpn parameter chosen here.

2024-06-05 23:31 UTC, sinui0 commented
> Maybe we can keep spcot and mpcot internal apis, since they are only called by ferret. In this case, we do not need to keep all the output in internal states, it is much easier to be integrated by ferret.

Yes, we can keep SPCOT and MPCOT private for now to simplify things. 

> As to finalize, I meant to explicitly close the extension procedure of ferret. In KOS, the state will automatically turn to Complete after the check procedure (if I understand correctly). While in ferret, it will always allow us to extend, unless we manually turn it off with finalize.

Ok, I see the intent now. I'm not sure if that is necessary though. For KOS we only do this because the consistency check is leaky and we did not see any proofs that leakage of Delta is bounded when running multiple extensions. For Ferret, my understanding is that extension can be performed indefinitely, is that correct?

2024-06-06 00:38 UTC, sinui0 commented on crates/mpz-ot/src/ferret/sender.rs
> +        setup_rcot: &mut impl RandomCOTSender<Ctx, Block>,
I mean that the MPCOT instance already owns an `RCOT`, so we shouldn't need to pass in another one here

2024-06-06 00:42 UTC, xiangxiecrypto commented on crates/mpz-ot/src/ferret/sender.rs
> +        setup_rcot: &mut impl RandomCOTSender<Ctx, Block>,
That is what I mentioned in the PR comment. We will use a different RCOT here, i.e., Ferret with smaller parameters, to bootstrap.

2024-06-26 12:51 UTC, closed without merging