Add IO wrapper for OLE
privacy-ethereum/mpz pull request #138
Opened 2024-05-20 13:48 UTC by th4s

This PR adds the async wrapper crate for OLE.

2024-05-20 18:38 UTC, sinui0 requested changes

2024-05-20 18:38 UTC, sinui0 commented on crates/mpz-ole/src/msg.rs
This wrapper type should not be needed unless you want the protocol to be able to branch, which it doesn't in this case

2024-05-20 18:38 UTC, sinui0 commented on crates/mpz-ole/src/lib.rs
> +}
Over time I've become "opaque error" pilled. Virtually all errors in `mpz` should just be opaque errors which do not allow the user to inspect them and try to recover. On a case by case basis we can decide to allow that if the need arises. Otherwise, their `Debug` implementation can provide debugging info in addition to logging errors via `tracing`

Something like:

```rust
#[derive(Debug, thiserror::Error)]
#[error("ole error: {kind}")]
pub struct OleError {
  kind: OleErrorKind,
  #[source]
  source: Option<Box<dyn Error + Send + Sync>>
}

// Private enum
pub(crate) enum OleErrorKind {
  Io,
  Core,
  ..
}
```

2024-05-20 18:38 UTC, sinui0 commented on crates/mpz-ole/src/rot/receiver.rs
> +    context: PhantomData<C>,
The struct shouldn't be coupled to a context

2024-05-20 18:38 UTC, sinui0 commented on crates/mpz-ole/src/rot/receiver.rs
> +    pub async fn preprocess(&mut self, ctx: &mut C, count: usize) -> Result<(), OLEError> {
```suggestion
    pub async fn preprocess<Ctx: Context>(&mut self, ctx: &mut Ctx, count: usize) -> Result<(), OLEError> {
```

2024-05-20 18:38 UTC, sinui0 commented on crates/mpz-ole/src/rot/receiver.rs
> +            ctx.io_mut().expect_next::<OLEMessage<F>>()
Not worth forking the thread for IO. You can just push the message into the IO buffer and then await the expected message which will potentially already be sitting in the IO buffer.

2024-05-20 18:38 UTC, sinui0 commented on crates/mpz-ole/src/rot/receiver.rs
> +use serde::{Deserialize, Serialize};
You can use `serio::{Serialize, Deserialize}` bounds

2024-05-20 18:38 UTC, sinui0 commented on crates/mpz-ole/src/rot/receiver.rs
> +pub struct OLEReceiver<const M: usize, const N: usize, T, F, C> {
I feel we can get rid of the const noise in the signature using associated types.

Eg.

```rust
// naming could use some thought
pub trait ByteRepr {
  type Serialized: AsRef<[u8]>;
}

impl ByteRepr for P256 {
  type Serialized = [u8; 32];
}
```

then use that bound elsewhere

```rust
impl<F: Field + ByteRepr>
```

Or just add it as a bound on `Field`

2024-05-20 18:39 UTC, sinui0 commented on crates/mpz-ole/src/lib.rs
> +pub trait OLESender<C: Context, F: Field> {
Let's be consistent with abbreviation across crates

```suggestion
pub trait OLESender<Ctx: Context, F: Field> {
```

2024-05-21 09:20 UTC, th4s commented on crates/mpz-ole/src/rot/receiver.rs
> +    context: PhantomData<C>,
Omg this works. I did not see it . The problem is that the `rot_receiver` depends on `Context`. But:
```rust
impl<const M: usize, const N: usize, T, F> OLEReceiver<M, N, T, F>
where
    F: Field + Serialize + Deserialize,
{
    /// Preprocesses OLEs.
    ///
    /// # Arguments
    ///
    /// * `count` - The number of OLEs to preprocess.
    pub async fn preprocess<C: Context>(
        &mut self,
        ctx: &mut C,
        count: usize,
    ) -> Result<(), OLEError>
    where
        T: RandomOTReceiver<C, bool, [u8; M]> + Send,
    {
        //...
    }
```

2024-05-21 09:37 UTC, th4s commented on crates/mpz-ole/src/lib.rs
> +}
Interesting. I will try it out. What advantages do you see with this approach?

2024-05-27 15:54 UTC, sinui0 requested changes
So clean :ok_hand: 

Couple requests

2024-05-27 15:54 UTC, sinui0 commented on crates/mpz-ole/src/ideal.rs
Let's stick to using the abstraction provided in `mpz-common` for ideal 2PC. Otherwise we end up with a lot of maintenance messing around with channels

2024-05-27 15:54 UTC, sinui0 commented on crates/mpz-ole/src/ideal.rs
> +pub struct IdealOLESender<F: Field> {
Trait bounds on structs should be avoided if possible

2024-05-27 15:54 UTC, sinui0 commented on crates/mpz-ole/src/lib.rs
> +    /// * `a_k` - The sender's OLE inputs.
`a_k` is a messy argument name, I think we should stick to `inputs` and the user can refer to the documented functionality to understand the relation

2024-05-27 15:54 UTC, sinui0 commented on crates/mpz-ole/src/lib.rs
> +    /// * `ctx` - The context, which provides IO channels.
Unnecessary detail

```suggestion
    /// * `ctx` - The context.
```

2024-05-27 15:54 UTC, sinui0 commented on crates/mpz-ole/src/lib.rs
> +}
I think we can do something like this:

```suggestion
impl Display for OLEError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self.kind {
            OLEErrorKind::OT => f.write_str("ot error"),
            ...
        }?;
        
        if let Some(source) = self.source.as_ref() {
          f.write_str(format!(" caused by: {source}"))?;
        }
        
        Ok(())
    }
}
```

2024-05-27 15:54 UTC, sinui0 commented on crates/mpz-ole/src/lib.rs
> +    }
For convenience:

```suggestion
    fn new<E>(kind: OLEErrorKind, source: E) -> Self 
    where
      E: Into<Box<dyn Error + Send + Sync>>,
    {
        Self {
            kind,
            source: Some(source.into()),
        }
    }
```

2024-05-27 15:54 UTC, sinui0 commented on crates/mpz-ole/src/rot/receiver.rs
> +                "Not enough OLEs available".into(),
lets include the number of OLEs there are, something like: `format!("{} < {}", self.core.len(), b_k.len())`

2024-05-27 15:54 UTC, sinui0 commented on crates/mpz-ole/src/rot/receiver.rs
> +    T: RandomOTReceiver<Ctx, bool, F::Serialized> + Send,
Bound isn't needed here

2024-05-27 15:54 UTC, sinui0 commented on crates/mpz-ole/src/rot/receiver.rs
> +            .collect();
Converting via the bit iterators is clunky. Let's either do it via an array conversion method, or change the OT bound to `RandomOTReceiver<Ctx, bool, F>` and find a way to have that available

2024-05-27 15:54 UTC, sinui0 commented on crates/mpz-ole/src/rot/sender.rs
> +                    F::from_lsb0_iter(b.as_ref().into_iter_lsb0()),
same here

2024-05-29 17:20 UTC, sinui0 approved these changes
:fire: :fire: 

Just 1 nit on needing newtypes for the ideal impl.

2024-05-29 17:20 UTC, sinui0 commented on crates/mpz-ole/src/ideal.rs
Please add newtypes here, eg:

```rust
pub struct IdealOleSender(Alice<()>);
pub struct IdealOleReceiver(Bob<()>);
```

2024-05-29 17:20 UTC, sinui0 commented on crates/mpz-ole/src/lib.rs
> +        }
Doesn't matter, but you could use `Self::new(OLEErrorKind::OT, value)`

2024-05-30 10:58 UTC, themighty1 approved these changes
gw!

2024-05-31 08:30 UTC, merged