refactor(mpz-garble): fix threading breaking changes
privacy-ethereum/mpz pull request #144
Opened 2024-05-29 02:31 UTC by sinui0

This PR refactors `mpz-garble` to accomodate the breaking changes from #112 .

# Changes
- Use new `Context` abstraction.
- Incorporate changes from #140 
- Remove `DEAPVm` type and just use `DEAPThread`

2024-06-03 09:49 UTC, th4s approved these changes
lgtm :+1:

2024-06-05 07:43 UTC, themighty1 requested changes
nice work!!! just one concern about feed vs send

2024-06-05 07:43 UTC, themighty1 commented on crates/mpz-garble/src/generator/mod.rs
> +                    io.feed(batch).await?;
Are we sure we need `feed` here instead of `send`? WIth `feed`, the gates will not be streamed until `flush` is called.

2024-06-05 07:43 UTC, themighty1 commented on crates/mpz-garble/src/protocol/deap/vm.rs
> +    /// If this instance is the leader this function returns the follower's
```suggestion
    /// If this instance is the leader, this function returns the follower's
```

2024-06-05 16:32 UTC, sinui0 commented on crates/mpz-garble/src/generator/mod.rs
> +                    io.feed(batch).await?;
@th4s and I discussed this and think that `feed` is correct here. We don't want to wait for the IO to flush before continuing to garble the next batch. There is a latency vs throughput tradeoff here, where worst case latency occurs when the garbled circuit is smaller than the IO buffer so it doesn't flush until garbling is complete. Otherwise, calling `feed` _will_ start flushing once the buffer is full. In our case the underlying connection is being polled concurrently so it will make progress between calls to `feed`.

2024-06-05 16:37 UTC, merged