fix(mpz-common): flush io in syncer
privacy-ethereum/mpz pull request #157
Opened 2024-06-12 18:20 UTC by sinui0

This PR fixes a bug in the syncers. The leader *must* flush the io before returning, otherwise it deadlocks. Also, the leader should be sending the ticket *before* executing the function/future.

2024-06-13 08:04 UTC, th4s approved these changes

2024-06-14 06:28 UTC, themighty1 requested changes
just need to clarify a few points

2024-06-14 06:28 UTC, themighty1 commented on crates/mpz-common/src/sync/async_syncer.rs
> +        let mut tick_lock = self.tick.lock().await;
I don't quite understand why we don't release the lock on the ticket as soon as possible?
The way it is coded now will make other tasks wait until this task completes.
I expect this:
```rust
let mut tick_lock = self.tick.lock().await;
let tick = tick_lock.increment_in_place(); 
drop(tick_lock);
io.send(tick).await?;
let output = fut.await;
```

2024-06-14 06:28 UTC, themighty1 commented on crates/mpz-common/src/sync/async_syncer.rs
> +        let mut tick_lock = self.tick.lock().await;
Additionally, I think we want to `join!(io.send(tick), fut)` in order to avoid the overhead of awaiting `io.send`

2024-06-14 07:45 UTC, sinui0 commented on crates/mpz-common/src/sync/async_syncer.rs
> +        let mut tick_lock = self.tick.lock().await;
The lock must be held until the task is finished otherwise competing CPU threads can budge in line. The purpose of the syncer is to make sure that any state mutation performed by a task is executed in the same order across machines.

I do agree, we can join on the futures for sending the ticket and executing the task. I'll update it

2024-06-14 09:14 UTC, themighty1 commented on crates/mpz-common/src/sync/async_syncer.rs
> +        let mut tick_lock = self.tick.lock().await;
Right, makes sense re the order of execution, thanks. Ok, lets wait for the update.

2024-06-14 17:11 UTC, merged