refactor(mpz-ot): ferret clean up
privacy-ethereum/mpz pull request #173
Opened 2024-07-05 04:54 UTC by sinui0

This PR does some simplification and clean up of the ferret impl.

# Changes

- Refactored to opaque error types
- Removed state from `spcot` and `mpcot` impls, making them functional
- Removed unnecessary generics
- Removed some unsatisfiable trait bounds, eg `RandomCOT: Default`
- Added buffering to the core types
- Implemented iterative extension with one-time bootstrapping using injected RCOT
  - This still needs work, from my understanding the iterations can be performed in parallel. Right now we're doing them sequentially and that will have poor round complexity.

2024-07-10 03:27 UTC, xiangxiecrypto commented on crates/mpz-ot/src/ferret/mod.rs
> +    }
```suggestion
    /// Returns the number of COTs required to bootstrap an extension.
    pub(crate) fn bootstrap_rate(&self) -> usize {
        self.lpn_parameters.k
    }
```

2024-07-10 03:33 UTC, xiangxiecrypto commented on crates/mpz-ot/src/ferret/mpcot.rs
> +        let n = 10;
The `alphas` values are not regular, so the test fails.
Try to use a regular `alphas` such as `[0, 3, 4, 7, 9]`

2024-07-10 04:38 UTC, xiangxiecrypto commented on crates/mpz-ot/src/ferret/sender.rs
> +            };
I do not think we should use `self.rcot` to generate COTs in this step. It will only be used in the setup phase.
One optimization is to reserve enough COTs in the previous ferret extension for the next extension, and just read them for this step like `BootstrappedSender`.

2024-07-10 05:30 UTC, xiangxiecrypto commented on crates/mpz-ot/src/ferret/sender.rs
> +            };
Note that the `k` COTs are already reserved in Sender state (see `v`).

2024-07-10 05:34 UTC, xiangxiecrypto commented on crates/mpz-ot/src/ferret/receiver.rs
> +            };
similar to Sender.

2024-07-10 05:35 UTC, xiangxiecrypto requested changes
It is much simpler and cleaner!

2024-08-16 01:23 UTC, xiangxiecrypto commented
Optimize the ferret extension process, rcot is only invoked in the setup phase, and buffer all the needed COTs in the extension phase.
@sinui0 Is there any example of using KOS with io? Then I can set all the real parameters for Ferret.

2024-08-16 02:07 UTC, sinui0 commented
ty @xiangxiecrypto sorry this is taking so long on my end, im almost ready to focus back here again.

Why move the buffering out into the io layer? Can't we use the existing buffer in core?

> Is there any example of using KOS with io? Then I can set all the real parameters for Ferret.

The tests in the kos module should give a sense of how to use the API. Or are you wondering how to use it with an actual network connection, eg TCP?

2024-08-16 02:07 UTC, sinui0 commented
I'm going to go ahead and merge this into the `ferret` branch and we can continue there

2024-08-16 02:08 UTC, merged