KOS Actor
privacy-ethereum/mpz pull request #50
Opened 2023-08-21 04:26 UTC by sinui0

This PR re-implements the KOS actors, removing our dependency on `xtra`. Keep in mind that these modules are already dead-on-arrival in a way, as we are going to be replacing them with SoftSpokenOT. Don't get too bogged down on all the edge-cases for now :slightly_smiling_face: 

# Changes
1. Adjusted the verifiable OT interface a bit to support parallel verification.
2. Added `Verify` as a typed state into the KOS receiver core, adding a bit of safety and saving the outer layer from having to manually distribute copies of $\Delta$
3. Implemented the actors.

2023-08-21 04:30 UTC, sinui0 commented
I will put tracing instrumentation into a separate PR

2023-08-23 16:16 UTC, th4s approved these changes
Good work :rocket:

I feel it would help understanding to put the actors and the remotes (`SharedSender`, `SharedReceiver`) into different modules.

2023-08-23 16:16 UTC, th4s commented on ot/mpz-ot/src/kos/sender.rs
> +    /// Returns a mutable refernce to the inner sender state.
typo: `reference`

2023-08-23 16:16 UTC, th4s commented on ot/mpz-ot/src/kos/receiver.rs
> +    /// Returns a mutable refernce to the inner receiver state.
typo: `reference`

2023-08-29 13:14 UTC, themighty1 requested changes
gw, the first 2 review items below are questions about the code, the rest are just comments.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/receiver.rs
> +                        return Ok(());
is `return Ok(());` by design? Is there anything wrong with both sending an error to the caller and also returning an error from the actor?

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/receiver.rs
> +                self.state.ids.insert(id.clone(), keys.id());
it's best to return an error on duplicate ids
```rust
if self.state.ids.insert(id.clone(), keys.id()).is_some() {
                    _ = caller_response.send(Err(ReceiverError::Other(format!(
                        "duplicate transfer id: {id}"
                    ))));
                    return Err(ReceiverError::Other(format!("duplicate transfer id: {id}")));
                }
```

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/kos/receiver.rs
> +        // Finalize cointoss to determine expected delta
coin toss

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/kos/sender.rs
> +        // If the sender is committed, we sample delta using a cointoss.
coin toss

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/receiver.rs
> +
/// Commands which can be received by [`ReceiverActor`].

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/receiver.rs
> +        choices: Vec<bool>,
/// Used to send back the `Result` to the caller of the `Receive` command.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/receiver.rs
> +    id: String,
/// Used to send back the `Result` to the caller of the `Verify` command.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/receiver.rs
> +
/// A pending oblivious transfer which was requested by this KOS receiver but has not yet been
/// responded to by the KOS sender.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/receiver.rs
> +    keys: ReceiverKeys,
/// Used to send back the `Result` to the caller of the `Receive` command.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/receiver.rs
> +struct Shutdown {
/// Used to send back the `Result` to the caller of the `Shutdown` command.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/receiver.rs
> +struct State {
/// All oblivious transfer ids seen so far.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/receiver.rs
> +pub struct ReceiverActor<BaseOT, Si, St> {
/// A sink to send messages to the KOS sender actor.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/receiver.rs
> +    sink: Si,
/// A stream to receive messages from the KOS sender actor.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/receiver.rs
> +
/// The sending end of the channel used by the controller to send commands to this actor.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/receiver.rs
> +    command_sender: mpsc::UnboundedSender<Command>,
/// The receiving end of the channel used by this actor to receive commands from the controller.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/receiver.rs
> +            futures::select! {
// Processes a message received from the Sender.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/receiver.rs
> +                msg = self.stream.select_next_some() => self.handle_msg(msg?).await?,
// Processes a command from the controller.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/receiver.rs
> +
/// Starts an oblivious transfer by sending a request to the peer.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/receiver.rs
> +
/// Handles the `Verify` command from the controller.
///
/// Sends back the [`PayloadRecord`] which the controller must verify itself.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/receiver.rs
> +        // If we're ready to start verifying we do so, otherwise, we buffer
comma before "we do so" missing

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/receiver.rs
> +
/// Handles commands received from the controller.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/receiver.rs
> +
/// Handles a message from the KOS sender actor.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/receiver.rs
> +pub struct SharedReceiver {
/// The sending end of the channel used to send commands to the actor.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/sender.rs
> +
/// Commands which can be received by [`SenderActor`].

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/sender.rs
> +    id: String,
/// Used to send back the `Result` to the caller of the `GetKeys` command.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/sender.rs
> +    payload: SenderPayload,
/// Used to send back the `Result` to the caller of the `PendingPayload` command.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/sender.rs
> +struct Shutdown {
/// Used to send back the `Result` to the caller of the `Shutdown` command.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/sender.rs
> +pub struct SenderActor<BaseOT, Si, St> {
/// A sink to send messages to the KOS receiver actor.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/sender.rs
> +    sink: Si,
/// A stream to receive messages from the KOS receiver actor.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/sender.rs
> +
/// The sending end of the channel used by the controller to send commands to this actor.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/sender.rs
> +    command_sender: mpsc::UnboundedSender<Command>,
/// The receiving end of the channel used by this actor to receive commands from the controller.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/sender.rs
> +                // Processes a command
// Processes a command from the controller.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/sender.rs
> +
/// Handles commands received from the controller.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/sender.rs
> +                } else {
// The peer has not requested an OT with this id yet.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/sender.rs
> +
/// Handles a message from the KOS receiver actor.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/sender.rs
> +/// KOS Shared Sender
/// KOS Shared Sender controller.

2023-08-29 13:14 UTC, themighty1 commented on ot/mpz-ot/src/actor/kos/sender.rs
> +pub struct SharedSender {
/// The sending end of the channel used to send commands to the actor.

2023-08-29 17:05 UTC, sinui0 commented on ot/mpz-ot/src/actor/kos/receiver.rs
> +                        return Ok(());
It's by design, I don't think the actor needs to be shut down as the error is specific to that particular call

2023-08-29 17:07 UTC, sinui0 commented on ot/mpz-ot/src/actor/kos/receiver.rs
> +                self.state.ids.insert(id.clone(), keys.id());
agreed, though as above I don't think this should shut down the actor with an error

2023-08-29 17:27 UTC, sinui0 commented on ot/mpz-ot/src/actor/kos/receiver.rs
> +                self.state.ids.insert(id.clone(), keys.id());
Fixed, but returns `Ok(())`

2023-08-30 06:07 UTC, themighty1 approved these changes

2023-08-30 17:39 UTC, merged