fix: clmul aarch64
privacy-ethereum/mpz pull request #74
Opened 2023-10-05 20:34 UTC by sinui0

This PR reorganizes some things and brings the `clmul` crate more inline with the original `polyval` crate.

# Changes
- Removes `armv8` and `force-soft` features in favor of using `RUSTFLAGS`
- Reorganizes modules to match `polyval` layout

2023-10-06 06:35 UTC, themighty1 requested changes
lgtm, a fix is needed

2023-10-06 06:35 UTC, themighty1 commented on clmul/src/backend/autodetect.rs
> +        let inner = if cfg!(clmul_force_soft) || !has_intrinsics {
if we don't have `intrinsics` and we didn't pass `clmul_force_soft`, this code will select `intrinsics` in the else{} branch below. But we need `soft` instead.

2023-10-06 06:35 UTC, themighty1 commented on clmul/src/backend/autodetect.rs
> +    pub fn clmul_reuse(&mut self, x: &mut Self) {
Im in favor of getting rid of this fn since the speedup doesnt apply anymore.

2023-10-06 06:35 UTC, themighty1 commented on clmul/Cargo.toml
> -[features]
There are some refs to `armv8` and `force-soft` dangling in the code and comments. 
Can we also document the new `clmul_armv8` and `clmul_force_soft` flags? We can document them here as a comment.

2023-10-06 16:32 UTC, sinui0 commented on clmul/src/backend/autodetect.rs
> +        let inner = if cfg!(clmul_force_soft) || !has_intrinsics {
Are you sure? This evaluates true if
 - force soft is enabled, or
 - instrinsics aren't available

2023-10-06 16:32 UTC, sinui0 commented on clmul/src/backend/autodetect.rs
> +    pub fn clmul_reuse(&mut self, x: &mut Self) {
I agree

2023-10-06 16:46 UTC, sinui0 commented on clmul/Cargo.toml
> -[features]
I documented them in the crate root docs

2023-10-09 06:00 UTC, themighty1 commented on clmul/src/backend/autodetect.rs
> +        let inner = if cfg!(clmul_force_soft) || !has_intrinsics {
you are right, sry

2023-10-09 06:00 UTC, themighty1 approved these changes
lgtm

2023-10-09 10:34 UTC, merged