add SPCOT in mpz-ot-core
privacy-ethereum/mpz pull request #77
Opened 2023-10-15 09:14 UTC by xiangxiecrypto

1. Add the SPCOT protocol in the `mpz-ot-core` crate.
2. MPZ now lacks COT traits and implementations. Therefore, the current PR uses an ideal functionality of COT (with random choices).
3. The network IO is not involved.

2023-10-15 17:02 UTC, sinui0 commented
Great, I'll review soon! Can you please rebase on `dev`?

2023-10-16 01:56 UTC, xiangxiecrypto commented
> Great, I'll review soon! Can you please rebase on `dev`?

Done

2023-10-18 00:37 UTC, sinui0 requested changes
Nice! Looking good, but I have some suggestions around type/state safety.

Right now both the `Sender` and `Receiver` only have two states: `Initialized` and `Extend`. I think it would be best to lean more into the type state pattern to enforce correctness here. We should be able to statically guarantee the protocol executes in the correct sequence.

Separately, rather than coupling the sender and receiver to the `CotMsgFor*` messages, we should just pass in the correlations/choices directly as input arguments.

2023-10-18 00:37 UTC, sinui0 commented on ot/mpz-ot-core/src/ferret/spcot/msgs.rs
> +}
These messages would be part of the underlying `COT` protocol, we shouldn't define them here

2023-10-18 00:37 UTC, sinui0 commented on ot/mpz-ot-core/src/ferret/spcot/msgs.rs
> +}
This protocol wraps a COT protocol, so we just add a variant for it. We can get rid of `BaseMsg` as that would be for a Base OT protocol which SPCOT doesn't use directly.

```suggestion
pub enum Message<CotMsg> {
    CotMsg(CotMsg),
    MaskBits(MaskBits),
    ExtendFromSender(ExtendFromSender),
    CheckFromReceiver(CheckFromReceiver),
    CheckFromSender(CheckFromSender),
}
```

2023-10-18 00:37 UTC, sinui0 commented on ot/mpz-ot-core/src/ferret/spcot/receiver.rs
> +        extend: CotMsgForReceiver,
```suggestion
        rs: &[bool],
```

2023-10-18 00:37 UTC, sinui0 commented on ot/mpz-ot-core/src/ferret/spcot/receiver.rs
> +        extendfc: CotMsgForReceiver,
Instead of depending on a concrete message type here, we can instead just depend on the correlations directly.

```suggestion
        ts: &[Block]
```

2023-10-18 00:37 UTC, sinui0 commented on ot/mpz-ot-core/src/ferret/spcot/sender.rs
> +        let hashed_v = Hash::from(*hasher.finalize().as_bytes());
We have a little helper function in `utils` which simplifies this, and `Hash` implements `From<[u8; 32]>`

2023-10-18 00:37 UTC, sinui0 commented on ot/mpz-ot-core/src/ferret/spcot/sender.rs
> +                "the length of q should be 128".to_string(),
`h` is an input argument and may not be 128. Is there a reason to not use a constant here?

2023-10-18 00:37 UTC, sinui0 commented on ot/mpz-ot-core/src/ferret/spcot/sender.rs
> +        ggm_tree.gen(s, &mut self.state.vs, &mut k0, &mut k1);
Multiple calls to `extend` will overwrite `self.state.vs`

2023-10-18 01:44 UTC, xiangxiecrypto commented on ot/mpz-ot-core/src/ferret/spcot/sender.rs
> +                "the length of q should be 128".to_string(),
It is a typo, the length of `q` should be `h`

2023-10-18 01:44 UTC, xiangxiecrypto commented on ot/mpz-ot-core/src/ferret/spcot/sender.rs
> +        ggm_tree.gen(s, &mut self.state.vs, &mut k0, &mut k1);
We should output `vs` after each call. 
Is it better that we make `vs` as the output of extend?

2023-10-18 01:48 UTC, sinui0 commented on ot/mpz-ot-core/src/ferret/spcot/sender.rs
> +        ggm_tree.gen(s, &mut self.state.vs, &mut k0, &mut k1);
`vs` should not be accessible until after the linear combination check has passed. This follows my suggestion at the top-level comment to introduce more states to make it impossible to misuse the API

2023-10-18 01:51 UTC, sinui0 commented on ot/mpz-ot-core/src/ferret/spcot/sender.rs
> +        ggm_tree.gen(s, &mut self.state.vs, &mut k0, &mut k1);
If you expect `extend` to be called multiple times prior to the check procedure, we can store them all internally until afterwards

2023-10-18 03:32 UTC, xiangxiecrypto commented on ot/mpz-ot-core/src/ferret/spcot/sender.rs
> +        ggm_tree.gen(s, &mut self.state.vs, &mut k0, &mut k1);
Well, let me fix it, and probably optimize the performance.

2023-10-19 13:21 UTC, xiangxiecrypto commented
1. Allow multiple calls of the `extend` function before `check`.
2. Optimize with batch check.
3. Optimize with Fiat-Shamir.

2023-10-20 00:10 UTC, sinui0 reviewed
Nice work, a couple comments

2023-10-20 00:10 UTC, sinui0 commented on ot/mpz-ot-core/src/ferret/spcot/receiver.rs
> +                "the length of x* should be 128".to_string(),
```suggestion
                format!("the length of x* should be {CSP}")
```

2023-10-20 00:10 UTC, sinui0 commented on ot/mpz-ot-core/src/ferret/spcot/receiver.rs
> +            .into_iter()
we can avoid double allocation

```suggestion
            .iter_lsb0()
```

2023-10-20 00:10 UTC, sinui0 commented on ot/mpz-ot-core/src/ferret/spcot/receiver.rs
> +        self.state.extended = true;
Is this method intended to be terminating? If so, we can receive `self` instead of `&mut self` in the method signature

2023-10-20 00:10 UTC, sinui0 commented on ot/mpz-ot-core/src/ferret/spcot/receiver.rs
> +    #[allow(missing_docs)]
unnecessary

2023-10-20 00:10 UTC, sinui0 commented on ot/mpz-ot-core/src/ferret/spcot/sender.rs
> +            });
Looks like we're iterating over `ms` twice, perhaps zip `k0` and `k1` into the first iterator?

2023-10-20 00:10 UTC, sinui0 commented on ot/mpz-ot-core/src/ferret/spcot/sender.rs
> +        self.state.extended = true;
Same here, we can terminate by receiving `self`

2023-10-20 00:10 UTC, sinui0 commented on ot/mpz-ot-core/src/ferret/spcot/receiver.rs
> +        alpha_bar_vec.drain(0..alpha_bar_vec.len() - h);
`alpha` is `usize` which will be different depending on the architecture. Is this ok?

Also you can avoid the vector allocation with `alpha.msb0_iter().take(usize::BITS - h)`

2023-10-20 00:10 UTC, sinui0 commented on ot/mpz-ot-core/src/ferret/mod.rs
> +}
This is handy, can we move this to `src/ideal/cot` module? It can be used elsewhere. It would also be nice to have a `new_with_delta` method to set a predetermined delta

2023-10-20 03:31 UTC, xiangxiecrypto commented on ot/mpz-ot-core/src/ferret/spcot/receiver.rs
> +        self.state.extended = true;
Yes, but I think we still need to update the state, maybe for further usage. So I keep it as `&mut self`

2023-10-20 03:31 UTC, xiangxiecrypto commented on ot/mpz-ot-core/src/ferret/spcot/receiver.rs
> +        alpha_bar_vec.drain(0..alpha_bar_vec.len() - h);
It should be ok to use `usize`, but I think fixing it as `u32` is safer.

should be `alpha.iter_msb0().skip(u32::BITS as usize - h)`

2023-10-20 03:32 UTC, xiangxiecrypto commented on ot/mpz-ot-core/src/ferret/mod.rs
> +}
good point

2023-10-20 04:21 UTC, sinui0 commented on ot/mpz-ot-core/src/ferret/spcot/sender.rs
> +            });
I find this a bit hard to follow with the multiple closures, perhaps a simple loop?

```suggestion
        // Computes M0 and M1.
        let mut ms: Vec<[Block; 2]> = Vec::with_capacity(qs.len());
        for (((i, &q), b), (k0, k1)) in qs.iter().enumerate().zip(bs).zip(k0.into_iter().zip(k1)) {
            let mut m = if b {
                [q ^ self.state.delta, q]
            } else {
                [q, q ^ self.state.delta]
            };

            let tweak: Block = bytemuck::cast([i, self.state.exec_counter]);
            FIXED_KEY_AES.tccr_many(&[tweak, tweak], &mut m);

            m[0] ^= k0;
            m[1] ^= k1;

            ms.push(m);
        }
```

2023-10-20 04:25 UTC, xiangxiecrypto commented on ot/mpz-ot-core/src/ferret/spcot/sender.rs
> +            });
Well, I used iter twice before to make the code more readable.
For functionality, all these ways are workable.

2023-10-20 04:27 UTC, sinui0 commented on ot/mpz-ot-core/src/ferret/spcot/sender.rs
> +            });
Sorry for being picky :grinning: The multiple closures iterates over `ms` 3 times I think (not sure if the compiler optimizes it away)

2023-10-20 04:34 UTC, xiangxiecrypto commented on ot/mpz-ot-core/src/ferret/spcot/sender.rs
> +            });
I think you are right on this point. Although I think the TCCR hash will dominate the performance, but I think it is always good to make possible optimizations.

2023-10-20 15:21 UTC, sinui0 approved these changes
Good work

2023-10-20 15:21 UTC, sinui0 commented on ot/mpz-ot-core/src/ideal/ideal_cot.rs
> +}
Please place into a `mod tests` module

2023-10-25 16:36 UTC, merged

2023-10-31 07:00 UTC, themighty1 reviewed
lgtm, will open a new PR for some minor fixes.