Add Ferret-core
privacy-ethereum/mpz pull request #90
Opened 2024-01-03 04:41 UTC by xiangxiecrypto

1. Add the core building blocks of Ferret (without network IO).
2. It can still be further optimized when integrated with network IO, which needs COT implementation.

2024-02-08 03:25 UTC, xiangxiecrypto commented
Let me merge `MPCOT` and update accordingly.

2024-02-08 03:47 UTC, sinui0 commented
#87 is merged, you should be able to rebase

2024-03-07 23:39 UTC, sinui0 requested changes
Nice! Just a couple minor adjustments needed, otherwise lgtm :)

2024-03-07 23:39 UTC, sinui0 commented on ot/mpz-ot-core/src/ferret/msgs.rs
> +}
We can discard this now, as we're redesigning our approach for IO. See #112 . Changes there removes the need for a wrapper enum

2024-03-07 23:39 UTC, sinui0 commented on ot/mpz-ot-core/src/ferret/sender.rs
> +        lpn_type: LpnType,
Can we move these to `new`?

2024-03-07 23:39 UTC, sinui0 commented on ot/mpz-ot-core/src/ferret/mod.rs
> +/// LPN parameters with unifom noise.
```suggestion
/// LPN parameters with uniform noise.
```

2024-03-07 23:39 UTC, sinui0 commented on ot/mpz-ot-core/src/ferret/sender.rs
> +        Ok(y[self.state.lpn_parameters.k..].to_vec())
```suggestion
        let y_ = y.split_off(self.state.lpn_parameters.k);

        // Update v to y[0..k]
        self.state.v = y;

        // Update counter
        self.state.counter += 1;

        Ok(y_)
```

2024-03-07 23:39 UTC, sinui0 commented on ot/mpz-ot-core/src/ferret/receiver.rs
> +        seed: Block,
These can be moved to `new` as well

2024-03-07 23:39 UTC, sinui0 commented on ot/mpz-ot-core/src/ferret/receiver.rs
> +                    bytemuck::cast(1_u128)
```suggestion
                    Block::ONE
```

Please add an associated const to `Block` so we don't rely on casts in places like this

2024-03-07 23:39 UTC, sinui0 commented on ot/mpz-ot-core/src/ferret/receiver.rs
> +        let mut x = self.state.e.to_vec();
```suggestion
        let mut x = self.state.e.clone();
```

2024-03-07 23:39 UTC, sinui0 commented on ot/mpz-ot-core/src/ferret/receiver.rs
> +        ))
```suggestion
        let mut x = x.iter().map(|a| a.lsb() == 1).collect::<Vec<bool>>();

        let x_ = x.split_off(self.state.lpn_parameters.k);
        let z_ = z.split_off(self.state.lpn_parameters.k);

        // Update u, w
        self.state.u = x;
        self.state.w = z;

        // Update counter
        self.state.counter += 1;

        Ok((x_, z_))
```

2024-03-07 23:39 UTC, sinui0 commented on ot/mpz-ot-core/src/ideal/ideal_mpcot.rs
> +    pub fn check(
Please pull out into a standalone function gated with `#[cfg(test)]`

2024-03-07 23:39 UTC, sinui0 commented on ot/mpz-ot-core/src/ideal/mod.rs
> +//! Define ideal functionalities of OTs.
duplicate line

2024-03-14 06:41 UTC, xiangxiecrypto commented on ot/mpz-ot-core/src/ferret/sender.rs
> +        lpn_type: LpnType,
Let us keep it here for now, the `new` function is only a default instantiation without any specific parameters.

2024-03-14 16:32 UTC, sinui0 approved these changes

2024-03-14 16:32 UTC, merged