Add RandomOT traits and implement them for KOS15
privacy-ethereum/mpz pull request #91
Opened 2024-01-15 14:53 UTC by th4s

This PR adds the traits `RandomOTSender` and `ChosenMessageRandomOTReceiver` and implements them for KOS15.

2024-01-16 00:27 UTC, sinui0 requested changes
Cool, seems pretty straight forward.

Can we get a test in there too?

2024-01-16 00:27 UTC, sinui0 commented on ot/mpz-ot/src/kos/mod.rs
> +}
We now have an AES PRG in `mpz-core` that implements `rand` traits (and takes a Block/16-byte seed). Let's use that

2024-01-16 00:27 UTC, sinui0 commented on ot/mpz-ot/src/lib.rs
> +}
We can just call this `RandomOTReceiver` and get rid of the warning. This is an interface and should not bring implementation details into consideration. It's on the user to understand the implications of how they are composing specific concrete implementations of these traits.

2024-01-16 00:27 UTC, sinui0 commented on ot/mpz-ot/src/lib.rs
> +/// The OT sender gets two messages which are guaranteed to be random by the protocol.
This trait promises no such properties about the messages other than they aren't chosen here. What distribution they are sampled from is up to the concrete implementation

2024-01-16 00:27 UTC, sinui0 commented on ot/mpz-ot/src/lib.rs
> +    async fn random_messages(&mut self, count: usize) -> Result<Vec<T>, OTError>;
```suggestion
    async fn send_random(&mut self, count: usize) -> Result<Vec<T>, OTError>;
```

2024-01-16 00:27 UTC, sinui0 commented on ot/mpz-ot/src/lib.rs
> +    async fn receive(&mut self, count: usize) -> Result<(Vec<T>, Vec<U>), OTError>;
```suggestion
    async fn receive_random(&mut self, count: usize) -> Result<(Vec<T>, Vec<U>), OTError>;
```

2024-01-16 00:27 UTC, sinui0 commented on ot/mpz-ot/src/lib.rs
> +    async fn receive(&mut self, count: usize) -> Result<(Vec<T>, Vec<U>), OTError>;
IO Channels?

2024-01-16 00:27 UTC, sinui0 commented on ot/mpz-ot/src/lib.rs
> +    async fn random_messages(&mut self, count: usize) -> Result<Vec<T>, OTError>;
IO Channels?

2024-01-16 17:45 UTC, sinui0 approved these changes
gw :+1:

2024-01-17 12:13 UTC, themighty1 requested changes
we need to discuss if the use of PRG can be avoided

2024-01-17 12:13 UTC, themighty1 commented on ot/mpz-ot/src/kos/receiver.rs
> +                    prg.fill_bytes(&mut out);
we should use PRG only if `out.len()` > `block.len()`, otherwise we can just use `block` as is without the PRG, since it is already random.

2024-01-17 12:13 UTC, themighty1 commented on ot/mpz-ot/src/kos/sender.rs
> +            prg.fill_bytes(&mut out);
same here

2024-01-17 12:13 UTC, themighty1 commented on ot/mpz-ot/src/lib.rs
> +    /// Outputs two random messages.
```suggestion
    /// Outputs pairs of random messages.
```

2024-01-17 12:13 UTC, themighty1 commented on ot/mpz-ot/src/lib.rs
> +    /// * `count` - The number of random messages to get.
```suggestion
    /// * `count` - The number of pairs of random messages to output.
```

2024-01-17 13:12 UTC, th4s commented on ot/mpz-ot/src/kos/receiver.rs
> +                    prg.fill_bytes(&mut out);
There is already another implementation for `<bool, Block>` instead of `<bool, [u8; N]>`.

What specific case do you have in mind? When `out.len() < block.len()` do you want to directly use the block and strip the bits accordingly?

2024-01-17 13:43 UTC, themighty1 commented on ot/mpz-ot/src/kos/receiver.rs
> +                    prg.fill_bytes(&mut out);
ah, i overlooked that <bool, Block> exists. no worries.

2024-01-17 13:43 UTC, themighty1 approved these changes

2024-01-17 13:48 UTC, merged