refactor: chunk KOS extend message
privacy-ethereum/mpz pull request #98
Opened 2024-02-01 20:46 UTC by sinui0

This PR refactors KOS impl to chunk the extension message sent from the Receiver to the Sender.

Closes #97 and https://github.com/tlsnotary/tlsn-utils/issues/10

2024-02-02 09:41 UTC, th4s reviewed
Wouldn't it be cleaner to handle this in a general way in our messaging layer? Then this change would apply to every sink and stream we are using, while at the same time not mixing the protocol code with IO stuff.

I am thinking of something like wrapper functions in our `IoSink` and `IoStream` traits, which break down the payload if needed.

2024-02-02 20:09 UTC, sinui0 commented
That thought certainly crossed my mind, but it didn't seem to be quite as straight forward.

1. The IO layer already breaks down the message into chunks. The limit we are running into is mostly regarding _deserialization_ and how much memory a received message is allowed to utilize. This limit needs to be specific to the application context and message type. We could add additional bounds to the IO traits to specify this, but that would make them harder to implement and use. This would be less of a problem with specialization, but that's not in the foreseeable future.
2. A less flexible middleground is to fork `tokio_util::codec::length_delimited::LengthDelimitedCodec` and make it aware of variant-level size limits, so we could specify a limit specifically for `Extend` at the codec level rather than baking this into the IO traits. I don't want to block increasing the TLSNotary protocol limit on this work.
3. I think at the end of the day the chunking will get baked into the callsite control flow anyhow. The optimal state of this code would be to *generate* the matrix in chunks, streaming them, and processing the chunks concurrently. That would require "chunk" message types anyhow. Given our deprecation plans, this is a simpler short-term remedy even if its not actually doing stream processing.

2024-02-06 16:47 UTC, th4s commented
Makes sense :+1:, I haven't put that much thought into it when I wrote that.

2024-02-06 17:03 UTC, th4s approved these changes
:+1:

2024-02-07 07:01 UTC, themighty1 requested changes

2024-02-07 07:01 UTC, themighty1 commented on ot/mpz-ot-core/src/kos/msgs.rs
> +    /// Splits the message into chunks.
```suggestion
    /// Returns an iterator over the chunks of the message.
```

2024-02-07 07:01 UTC, themighty1 commented on ot/mpz-ot-core/src/kos/mod.rs
> +/// Returns the size in bytes of the extension message for a given number of OTs.
```suggestion
/// Returns the size in bytes of the extension matrix for a given number of OTs.
```

2024-02-07 07:01 UTC, themighty1 commented on ot/mpz-ot/src/kos/sender.rs
> +            extend.us.extend(chunk);
Is this correct?
The receiver was splitting off from the end of the matrix, so the first chunk which arrives must go to the end of the reconstructed matrix, not to the beginning as it is here.

2024-02-07 07:09 UTC, sinui0 commented on ot/mpz-ot/src/kos/sender.rs
> +            extend.us.extend(chunk);
Woh, what... how do the unit tests pass? I'll look into it

2024-02-07 07:16 UTC, sinui0 commented on ot/mpz-ot/src/kos/sender.rs
> +            extend.us.extend(chunk);
Good catch, the unit tests don't setup enough OTs to hit the chunk threshold.

2024-02-10 00:01 UTC, sinui0 commented on ot/mpz-ot/src/kos/sender.rs
> +            extend.us.extend(chunk);
Fixed.

2024-02-12 11:09 UTC, themighty1 requested changes

2024-02-12 11:09 UTC, themighty1 commented on ot/mpz-ot/src/kos/receiver.rs
> +            let extend = ext_receiver.extend(count);
padding should not happen inside .extend() again

2024-02-12 11:09 UTC, themighty1 commented on ot/mpz-ot/src/kos/receiver.rs
>          // Extend the OTs, adding padding for the consistency check.
this comment is not accurate anymore

2024-02-12 19:43 UTC, sinui0 commented on ot/mpz-ot/src/kos/receiver.rs
> +            let extend = ext_receiver.extend(count);
I've removed the rounding that occurs in the core impl and replaced it with an input restriction to be a multiple of 64. This subtlety is not exposed to the user of the async wrapper.

2024-02-13 07:45 UTC, themighty1 approved these changes
gw

2024-02-13 14:51 UTC, merged